### ISSUE TITLE
Debugging session expires shortly after using the vpn trick

### ISSUE THREAD

**Issue by Redd12345** [osy/Jitterbug#10]
When ever I debug DolphiniOS with the vpn self debugging in 1.1.0, it works but shortly after (about 30 seconds) the session expires and the game crashes. I’ve re installed dolphin and jitterbug multiple time and it still doesn’t work. Using a normal debugging session with Libimobiledevice works fine without crashes.

**Comment by ViRb3** [comment]
You need to switch back to JitterBug immediately after starting your game so that JitterBug can detach from the game. Then you can switch back and play as long as you want. This is necessary because JitterBug, like all iOS apps, cannot run in the background, so as soon as the game opens, JitterBug stops executing, and it cannot perform the detach.

**Comment by jankais3r** [comment]
Might be worth to implement location-based background activity for Jitterbug, as this will be a major annoyance and source of support tickets. Apps like [iSH](https://github.com/ish-app/ish/wiki/Running-in-background) successfully use location tracking to stay active in the background.
