### ISSUE TITLE
How do I use VPN tunnel ?

### ISSUE THREAD

**Issue by LukasAppleFan** [osy/Jitterbug#26]
Hi,
I was able to successfully configure the tool to play Wii games on iPad at full speed. But I have a paid developer account and I wanted to know how I can configure the VPN tunnel ?
Do I just use the generated file from my Mac on the SAME device instead of secondary ?
Thanks in advance.

**Comment by osy** [comment]
Yes, and make sure you sign or build with the right profile.

**Comment by LukasAppleFan** [comment]
Thanks for your reply, I use Sideloadly to install the IPA using my paid dev account. Is it enough or do I actually have to build it from source and follow instructions to get the entitlements ?
Btw do both devices have to be connected to same Wi-Fi ?
Because let's say I use data sharing then the iPad will be connected to iPhone with the iPhone will have access to internet but on 4G.

**Comment by LukasAppleFan** [comment]
I tried but I got this![image](https://user-images.githubusercontent.com/41242166/133881812-f0e5ae89-759a-4445-a566-83eda0d4b408.jpeg)

**Comment by LukasAppleFan** [comment]
And let's say I only have my iPad without any internet connection but I have the dev account can I still run Jitterbug VPN ? (If I can figure out how to set it up)

**Comment by LukasAppleFan** [comment]
Well I actually build from source and it gave me the option to use VPN tunnel.
Weird that Sideloadly will not sign it properly.

**Comment by SugarRayLua** [comment]
Thanks, LukasAppleFan.

I think I figured out what the issue is for me. I use a resigning service (Signulous) to obtain my paid dev account and realized that many of the resigning services don’t routinely include the ability to add the “Network Extensions Entitlement” as confirmed by their response to my support query:

"Glad you're enjoying our service! Signulous depends on provisioning files with wildcard app identifiers in order to be able to install an unlimited number of apps, and these provisioning files don't support custom entitlements due to limitations from Apple. However, if you are willing to sign the app yourself on your Mac and only need it for one app identifier, I can get you a custom provisioning file for your device that supports custom entitlements including network extensions. If you’d like to give it a try, please let me know your device's UDID.

Regards,
Signulous”

They are sending me a custom provisioning file, and I am going to try installing Jitterbug with that and see if that works. Otherwise, I believe some of the other resigning services for paid dev accounts are able to add the network extensions entitlement. Unfortunately, I’m not able to build from source and use Xcode as my Mac and Xcode are too old to create a iOS 15 app. I’ll let you and the other users know if I get the VPN tunnel working using the custom provisioning file that Signulous sends me as other users might wish to do the same. 

Sincerely,

Mike

**Comment by Eun** [comment]
Hello @SugarRayLua do you got it working with a custom provisioning file?

**Comment by SugarRayLua** [comment]
Hi, @Eun, yes I did. 

Sorry I didn't update this post with that information-- it seems like so long ago (and it was only 8 months ago) :-). I also thought I wrote a step by step post somewhere of how I did it but now can't seem to find it :-( and my memory of the exact steps is fading.

However, it turned out that to run the VPN tunnel you actually need a certificate with "entitlements" and not just a "custom provisioning file". The only place I could find on the web that you can purchase such a certificate with "entitlements" is at the UDID website:

https://www.udidregistrations.com/buy

Singulous and the other certificate signing services I believe do not sell certificates with the "entitlements" you need to set up on device VPN tunnel. I think (but not sure) the only other place to get a certificate with "entitlements" is to set up a higher tier development account with Apple. 

Once you have such a certificate (e.g. a certificate with "entitlements" from the UDID site) you can then manually sign the certificate with those entitlements and get the VPN tunnel to work. Unfortunately, that is where my memory is now hazy in terms of the exact steps to do that. I remember actually importing the UDID certificate I got with its entitlements into UTM and then using a Linux signing pkg I downloaded to sign the certificates (but unfortunately now don't remember the name of it). I believe you can also sign certificates with entitlements via Xcode signing tools on the Mac but I never did that because at that time my Mac was old and Xcode was out of date. 

I hope at least that helps get you started. The VPN tunnel has been working well on my iPad with UTM ever since. If I can find the document where I outline the exact steps I did, I'll add it to this post and cc: you.

Good luck!
