### ISSUE TITLE
VPN tunnel failed to start

### ISSUE THREAD

**Issue by Nanoc-ice** [osy/Jitterbug#31]
Primary: iPad Pro 3rd generation
iOS 15.0
latest version of Jitterbug
built using paid developer account with Xcode 13

Secondary: iPhone 13 Pro Max
iOS 15.02
Latest version of Jitterbug
built using paid developer account with Xcode13

I transferred the mobile device pairing file that was generated for my secondary device and copied it to my primary device.  All Good there.  When I bring up Jitterbug it sees my secondary device.

Next is what I don’t understand.  Does the app coming from my secondary device HAVE to be installed on my secondary device?  Or, can I not get it from the download files within my Files app?  I don’t see anyway to get at it, except if the app was install on the secondary device.  

Assuming you can get the app on the primary it says (I assume run it, in my case UTM), to click on the developerDisk…dmg
it is not clickable.  I believe I read it right that those to files (signature and dmg) needed to go on the primary.  Will it become available when the app is selected.

And the crux of the issue.  How to get the tunnel to work???  The network entitlement was built into the Jitterbug build.
So I don’t know what is wrong as the dialog box just says, VPN tunnel failed to start.

**Comment by KorEmla** [comment]
Sorry that I am asking to a question that is closed.
I am having an issue of 'Failed to start and application'.
I signed the iPA with iOS App Signer and I have a Apple Developer Account.
When I first open the Application (sideloaded with xcode), I am able to turn on VPN, Pair it, and Mount the DeveloperDiskImage. However, whenever I try to start an application, this error comes 'Failed to start an application'.
Any solution for this???
And also I will try to build Jitterbug with Mac and build it on iPad. However, I am keep having an error of
'Build input file cannot be found: '/Users/(My name)/Documents/Jitterbug/Libraries/libplist/src/(file name)'
Please help me.

**Comment by SugarRayLua** [comment]
Hi, @KorEmla. My thought as a novice user (who spent a while trying different solutions) is that your ‘Failed to start an application’ stems from one of two things:
1) Developer Disk Image does not match the iOS you are trying to run UTM in or
2) The app has been fully signed correctly due to the limitations of the Developer certificate you are trying to sign the app with

In my experience when either of the above are not correct, the UTM “almost” works but not all the way like you are mentioning. I don’t know if you are using the latest iOS or not and whether the latest iOS DeveloperDiskImage was posted on the internet, but it hadn’t been when I first updated to the newest iPad iOS. I ended up downloading Xcode from Apple directly and extracting the DeveloperDiskImage to run UTM with the latest iPadOS.

My MAC is unfortunately too old to either use iOS App signer on the MAC or to build Jitterbug with Xcode. The key to successfully use the VPN function though is that you need to have a developer certificate AND a custom mobile profile to be able to successfully use the VPN function (unless perhaps your have your paid developer certificate directly from Apple). None of the regular resigning services that I could find except UDID Registrations would seem the developer certificate and that custom mobile profile that you need to get the VPN working correctly. 

If you primarily would like to still try and sign the certificates with iOS App Signer on your MAC or build on your MAC with Xcode, perhaps someone else on the group could give you some additional pointers. If you have access though to a Linux machine (or even using your Linux guest on your UTM app on your iPad— which is what I did), I’d continue to recommend installing the Github zsign package— worked very well for me and pretty straightforward. I’ve recopied the steps I did to use zsign to successfully sign and get Jitterbug’s VPN to work:

Go to 'UDID Registrations' site & buy Platinum account ($20/yr). That gives you Paid Dev cert & custom profile (need the latter to get VPN working on same device).

Determine 'bundle id' of the custom profile you bought.

Download & install zhlynn/zsign linux signer (I put in linux in UTM).

Put cert & custom profile & downloaded Jitterbug.ipa in same folder.

CLI: zsign -k Cert.p12 -p password -m CustomProfile -o signed.ipa -b 'bundleIDnamefromcustomprofile' Jitterbug.ipa

Install signed.ipa on your device (I use https://diawi.com).

Follow osy's instructions on GitHub site to import pairings and support files as you mentioned in your post.

I hope that helps :-)

**Comment by SugarRayLua** [comment]
Sorry for the typographical error— I meant to write:
2. The app has not been fully signed correctly…
